version: "3.8"
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ARF
      POSTGRES_PASSWORD: ARF
      POSTGRES_DB: ARF
    restart: always
    networks:
      - app-router-features
networks:
  app-router-features:
